confectionar/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('olga.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

olga/urls.py
from django.urls import path

from olga.views import ProductsView, IndexView, single

app_name = 'olga'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('products/', ProductsView.as_view(), name='products'),
    path('products/<int:category_id>/', ProductsView.as_view(), name='category'),
    path('page/<int:page>/', ProductsView.as_view(), name='paginator'),
    path('products/<slug:products_slug>/', single, name='single'),
]

users/urls.py
from django.urls import path

from users.views import (EmailVerificationView, UserLoginView,
                         UserRegisterView, basket_add, basket_remove, logout,
                         profile)

app_name = 'users'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('profile/', profile, name='profile'),
    path('baskets/add/<int:product_id>/', basket_add, name='basket_add'),
    path('basket/remove/<int:basket_id>/', basket_remove, name='basket_remove'),
    path('logout/', logout, name='logout'),
    path('verify/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='email_verification'),
]

olga/models.py
from django.db import models
from django.urls import reverse

from users.models import User


class CategoryModel(models.Model):
    category = models.CharField(max_length=100, unique=True, verbose_name='категория')
    description = models.CharField(max_length=250, null=True, blank=True, verbose_name='описание')

    class Meta:
        verbose_name_plural = 'категории'
        verbose_name = 'категория'

    def __str__(self):
        return self.category


class ProductsModel(models.Model):
    products = models.CharField(max_length=150, unique=True, verbose_name='продукт')
    slug = models.SlugField(verbose_name='URL', unique=False)
    description = models.CharField(max_length=250, null=True, blank=True, verbose_name='описание')
    price = models.DecimalField(max_digits=6, decimal_places=2, verbose_name='цена')
    quantity = models.PositiveIntegerField(default=0, verbose_name='количество')
    image = models.ImageField(upload_to='products_image')
    category = models.ForeignKey(CategoryModel, on_delete=models.CASCADE, related_name='productsmodel')

    class Meta:
        verbose_name_plural = 'продукты'
        verbose_name = 'продукт'

    def __str__(self):
        return self.products

    def get_absolute_url(self):
        return reverse('olga:single', kwargs={'products_slug': self.slug})


class BasketQuerySet(models.QuerySet):

    def total_sum(self):
        return sum(basket.sum() for basket in self)

    def total_quantity(self):
        return sum(basket.quantity for basket in self)


class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='пользователь')
    product = models.ForeignKey(ProductsModel, on_delete=models.CASCADE, verbose_name='продукт')
    quantity = models.PositiveIntegerField(default=0, verbose_name='количество')
    created_timestamp = models.DateTimeField(auto_now_add=True)
    objects = BasketQuerySet.as_manager()

    def __str__(self):
        return self.user.username

    def sum(self):
        return self.quantity*self.product.price

olga/views.py
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView, TemplateView

from olga.models import CategoryModel, ProductsModel


class IndexView(TemplateView):
    template_name = 'olga/index.html'


class ProductsView(ListView):
    template_name = 'olga/products.html'
    model = ProductsModel
    paginate_by = 3

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductsView, self).get_context_data()
        context['categories'] = CategoryModel.objects.all()
        context['baskets'] = CategoryModel.objects.all()
        return context

    def get_queryset(self):
        queryset = super(ProductsView, self).get_queryset()
        category_id = self.kwargs.get('category_id')
        return queryset.filter(category_id=category_id) if category_id else queryset


def single(request, products_slug):
    product_single = get_object_or_404(ProductsModel, slug=products_slug)
    product = ProductsModel.objects.filter(slug=products_slug)
    context = {'product_single': product_single,
               'products': product}
    return render(request, 'olga/single.html', context)

olga/templates/olga/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

    {% block css %}
    {% endblock css %}

    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-blue bg-dark fixed-top">
        <nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'olga:index' %}">CAKES FROM Olga</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'olga:index' %}">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'olga:products' %}">Магазин</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Контакты</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Профиль
                            </a>
                            <ul class="dropdown-menu">
                                {% if user.is_authenticated %}
                                    <li><a class="dropdown-item" href="{% url 'users:profile' %}">Корзина</a></li>
                                    <li><a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a></li>
                                    {% if user.is_superuser or user.is_stuff %}
                                        <li><a class="dropdown-item" href="{% url 'admin:index' %}">Админ-панель</a></li>
                                    {% endif %}
                                {% else %}
                                    <li><a class="dropdown-item" href="{% url 'users:login' %}">Войти</a></li>
                                    <li><a class="dropdown-item" href="{% url 'users:register' %}">Регистрация</a></li>
                                {% endif %}
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </nav>

    {% block content %}
    {% endblock content %}

    {% block scripts %}
    {% endblock scripts %}
</body>
</html>

olga/templates/olga/index.html
{% extends 'olga/base.html' %}
{% load static  %}


{% block css %}
    <link href="{% static 'vendor/css/index.css' %}" rel="stylesheet">
{% endblock css %}

olga/templates/olga/products.html
{% extends 'olga/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'vendor/css/products.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}
    <!-- Page Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <h1 class="my-4">CAKES FROM Olga</h1>
                <div class="list-group">
                    {% for category in categories %}
                        <a href="{% url 'olga:category' category.id %}" class="list-group-item">{{ category }}</a>
                    {% endfor %}
                </div>
            </div>
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">
                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <div class="carousel-indicators mt-10">
                      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
                    </div>
                    <div class="carousel-inner">
                      <div class="carousel-item active">
                        <img src="{% static 'vendor/img/pictures.jpg' %}" class="d-block w-100" alt="...">
                      </div>
                      <div class="carousel-item">
                        <img src="{% static 'vendor/img/pictures1.jpg' %}" class="d-block w-100" alt="...">
                      </div>
                      <div class="carousel-item">
                        <img src="{% static 'vendor/img/pictures2.jpg' %}" class="d-block w-100" alt="...">
                      </div>
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="visually-hidden">Next</span>
                    </button>
                </div>

                <div class="row">
                {% for product in object_list %}
                    <div class="col-lg-4 col-md-6 mb-4">
                        <div class="card h-100">
                            <a href="{{ product.get_absolute_url }}">
                                <img class="card-img-top"
                                     src="{{ product.image.url }}"
                                     alt="">
                            </a>
                            <div class="card-body">
                                <h4 class="card-title">
                                    <a href="{{ product.get_absolute_url }}">{{ product.products }}</a>
                                </h4>
                                <h5>{{ product.price }} руб.</h5>
                                <p class="card-text">{{ product.description|truncatechars:50 }}</p>
                            </div>
                            <div class="card-footer text-center">
                                <button type="button" class="btn btn-outline-success">
                                    <a href="{% url 'users:basket_add' product.id %}">Отправить в корзину</a>
                                </button>
                            </div>
                        </div>
                    </div>
                {% endfor %}

                {% if is_paginated %}
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-center">
                            {% if page_obj.has_previous %}
                                <li class="page-item"><a class="page-link" href="{% if page_obj.has_previous %} {% url 'olga:paginator' page_obj.previous_page_number %} {% else %} # {% endif %}">Предыдущая</a></li>
                            {% endif %}

                            {% for page in paginator.page_range %}
                                <li class="page-item"><a class="page-link" href="{% url 'olga:paginator' page %}">{{ page }}</a></li>
                            {% endfor %}

                            {% if page_obj.has_next %}
                                <li class="page-item"><a class="page-link" href="{% if page_obj.has_next %} {% url 'olga:paginator' page_obj.next_page_number %} {% else %} # {% endif %}">Следующая</a></li>
                            {% endif %}
                        </ul>
                    </nav>
                {% endif %}
            </div>
        </div>
    </div>
<!-- /.container -->
{% endblock content %}

olga/templates/olga/single.html
{% extends 'olga/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'vendor/css/products.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}
<div class="container">
    <div class="row">
        {% for product in products %}
            <div class="col-lg-5">
                <h1 class="my-4 text-center">{{ product.products }}</h1>
                <div class="list-group">
                    <img src="{{ product.image.url }}">
                </div>
            </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-7">
            <h2 class="my-4">{{ product.description }}</h2>
                <div class="list-group">
                    <h3>{{ product.price }} руб.</h3>
                    <div class="card-footer">
                            <button type="button" class="btn btn-outline-success">Отправить в корзину</button>
                    </div>
                </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}