confectionar/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('olga.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

olga/urls.py
from django.urls import path

from olga.views import ProductsView, IndexView, single

app_name = 'olga'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('products/', ProductsView.as_view(), name='products'),
    path('products/<int:category_id>/', ProductsView.as_view(), name='category'),
    path('page/<int:page>/', ProductsView.as_view(), name='paginator'),
    path('products/<slug:products_slug>/', single, name='single'),
]

orders/urls.py
from django.urls import path
from orders.views import OrderCreateView


app_name = 'orders'

urlpatterns = [
    path('create/', OrderCreateView.as_view(), name='order_create'),

]

users/urls.py
from django.urls import path

from users.views import (EmailVerificationView, UserLoginView,
                         UserRegisterView, basket_add, basket_remove, logout,
                         profile)

app_name = 'users'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('profile/', profile, name='profile'),
    path('baskets/add/<int:product_id>/', basket_add, name='basket_add'),
    path('basket/remove/<int:basket_id>/', basket_remove, name='basket_remove'),
    path('logout/', logout, name='logout'),
    path('verify/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='email_verification'),
]

users/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.db import models
from django.urls import reverse
from django.utils.timezone import now


class User(AbstractUser):
    image = models.ImageField(upload_to='user_image', null=True, blank=True)
    is_verification = models.BooleanField(default=True)

    def __str__(self):
        return self.username


class EmailVerification(models.Model):
    code = models.UUIDField(unique=True)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    expiration = models.DateTimeField()

    def __str__(self):
        return f'EmailVerification object for {self.user.email}'

    def send_verification_email(self):
        link = reverse('users:email_verification', kwargs={'email': self.user.email, 'code': self.code})
        verification_link = f'{settings.DOMAIN_NAME}{link}'
        subject = f'Подверждение учетной записи для {self.user.username}'
        message = 'Для подверждения учетной записи для {} перейдите по ссылке: {}'.format(
            self.user.email,
            verification_link
        )
        send_mail(
            subject=subject,
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[self.user.email],
            fail_silently=False,
        )

    def is_expired(self):
        return True if now() >= self.expiration else False

    class Meta:
        verbose_name_plural = 'авторизация'

users/forms.py
import uuid
from datetime import timedelta

from django import forms
from django.contrib.auth.forms import (AuthenticationForm, UserChangeForm,
                                       UserCreationForm)
from django.utils.timezone import now

from users.models import EmailVerification, User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Введите имя пользователя'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control', 'placeholder': 'Введите пароль'}))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Введите имя'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Введите фамилию'}))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Введите имя пользователя'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control', 'placeholder': 'Введите адрес эл. почты'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control', 'placeholder': 'Введите пароль'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control', 'placeholder': 'Подтвердите пароль'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=True)
        expiration = now() + timedelta(hours=48)
        record = EmailVerification.objects.create(code=uuid.uuid4(), user=user, expiration=expiration)
        record.send_verification_email()
        return user


class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'custom-file-label'}), required=False)
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': True}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'form-control', 'readonly': True}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'image', 'username', 'email')

users/views.py
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, TemplateView

from olga.models import Basket, ProductsModel
from users.forms import UserLoginForm, UserProfileForm, UserRegistrationForm
from users.models import EmailVerification, User


class UserLoginView(LoginView):
    template_name = 'users/login.html'
    form_class = UserLoginForm
    title = 'Store - Авторизация'


class UserRegisterView(CreateView):
    model = User
    form_class = UserRegistrationForm
    template_name = 'users/registration.html'
    success_url = reverse_lazy('olga:index')


@login_required
def profile(request):
    if request.method == 'post':
        form = UserProfileForm(instance=request.user, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:profile'))
    else:
        form = UserProfileForm(instance=request.user)

    baskets = Basket.objects.filter(user=request.user)
    total_sum = sum([basket.sum() for basket in baskets])
    total_quantity = sum(basket.quantity for basket in baskets)

    context = {'form': form,
               'baskets': baskets,
               'total_sum': total_sum,
               'total_quantity': total_quantity
               }
    return render(request, 'users/profile.html', context)


def basket_add(request, product_id):
    if request.user.is_authenticated:
        product = ProductsModel.objects.get(id=product_id)
        baskets = Basket.objects.filter(user=request.user, product=product)

        if not baskets.exists():
            Basket.objects.create(user=request.user, product=product, quantity=1)
        else:
            basket = baskets.first()
            basket.quantity += 1
            basket.save()
        return HttpResponseRedirect(request.META['HTTP_REFERER'])
    else:
        return HttpResponseRedirect(reverse('users:profile'))


def basket_remove(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    basket.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('olga:index'))


class EmailVerificationView(TemplateView):
    title = 'Store - Подтверждение электронной почты'
    template_name = 'users/email_verivication.html'

    def get(self, request, *args, **kwargs):
        code = kwargs['code']
        user = User.objects.get(email=kwargs['email'])
        email_verifications = EmailVerification.objects.filter(user=user, code=code)
        if email_verifications.exists() and not email_verifications.first().is_expired():
            user.is_verified_email = True
            user.save()
            return super(EmailVerificationView, self).get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('index'))

users/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Store - Авторизация</title>
    <link href="{% static 'vendor/css/auth.css' %}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>

{% block content %}
{% endblock content %}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'vendor/js/auth-admin.js' %}"></script>
</body>
</html>

users/templates/users/basket.html
{% extends 'olga/base.html' %}
{% load static %}

{% block content %}
  <div class="row">
    <div class="col-75">
      <div class="container">
        <form action="/action_page.php">

          <div class="row">
            <div class="col-50">
              <h3>Платежный адрес</h3>
              <label for="fname"><i class="fa fa-user"></i>Имя</label>
              <input type="text" id="fname" name="firstname" placeholder="Щипунов Андрей Леонидович">
              <label for="email"><i class="fa fa-envelope"></i> Email</label>
              <input type="text" id="email" name="email" placeholder="and-shhipunov@mail.ru">
              <label for="adr"><i class="fa fa-address-card-o"></i>Адрес</label>
              <input type="text" id="adr" name="address" placeholder="Томская 44-39">
              <label for="city"><i class="fa fa-institution"></i>Город</label>
              <input type="text" id="city" name="city" placeholder="Пермь">

              <div class="row">
                <div class="col-50">
                  <label for="state">Государство</label>
                  <input type="text" id="state" name="state" placeholder="Россия">
                </div>
                <div class="col-50">
                  <label for="zip">Zip</label>
                  <input type="text" id="zip" name="zip" placeholder="10001">
                </div>
              </div>
            </div>

            <div class="col-50">
              <h3>Платеж</h3>
              <label for="fname">Допустимые карты</label>
              <div class="icon-container">
                <i class="fa fa-cc-visa" style="color:navy;"></i>
                <i class="fa fa-cc-amex" style="color:blue;"></i>
                <i class="fa fa-cc-mastercard" style="color:red;"></i>
                <i class="fa fa-cc-discover" style="color:orange;"></i>
              </div>
              <label for="cname">Имя на карте</label>
              <input type="text" id="cname" name="cardname" placeholder="Щипунов Андрей Леонидович">
              <label for="ccnum">Номер кредитной карты</label>
              <input type="text" id="ccnum" name="cardnumber" placeholder="1111-2222-3333-4444">
              <label for="expmonth">Годен месяц</label>
              <input type="text" id="expmonth" name="expmonth" placeholder="Сентябрь">

              <div class="row">
                <div class="col-50">
                  <label for="expyear">Годен год</label>
                  <input type="text" id="expyear" name="expyear" placeholder="2021">
                </div>
                <div class="col-50">
                  <label for="cvv">CVV</label>
                  <input type="text" id="cvv" name="cvv" placeholder="352">
                </div>
              </div>
            </div>

          </div>
          <label>
            <input type="checkbox" checked="checked" name="sameadr"> Адрес дставки совпадает с платежным адресом
          </label>
          <input type="submit" value="Продолжить оформление заказа" class="btn">
        </form>
      </div>
    </div>

    <div class="col-25">
      <div class="container">
        <h4>Корзина
          <span class="price" style="color:black">
            <i class="fa fa-shopping-cart"></i>
            <b>4</b>
          </span>
        </h4>
        <p><a href="#">Элемент 1</a> <span class="price">$15</span></p>
        <p><a href="#">Элемент 2</a> <span class="price">$5</span></p>
        <p><a href="#">Элемент 3</a> <span class="price">$8</span></p>
        <p><a href="#">Элемент 4</a> <span class="price">$2</span></p>
        <hr>
        <p>Всего <span class="price" style="color:black"><b>$30</b></span></p>
      </div>
    </div>
  </div>
{% endblock %}

users/templates/users/email_verivication.html
{% extends 'users/base.html' %}


{% block content %}
    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header"><h3 class="text-center font-weight-light my-4">Поздравляем</h3>
                        </div>
                        <div class="card-body text-center">
                            <h4>Ваша учетная запись успешно подтверждена!</h4>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small"><a href="{% url 'olga:index' %}">Продолжить</a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

users/templates/users/login.html
{% extends 'users/base.html' %}
{% load static %}
{% load socialaccount %}


{% block css %}
    <link href="{% static 'vendor/css/profile.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}
    <div id="layoutAuthentication">
        <div id="layoutAuthentication_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-5">
                            {% if form.non_fields_errors %}
                                <div class="alert alert-warning alert-dismissible fade show" role="alert"
                                     style="margin-top: 100px;">
                                    {{ form.non_field_errors }}
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endif %}
                            <div class="card shadow-lg border-0 rounded-lg mt-5">
                                <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3>
                                </div>
                                <div class="card-body">
                                    <form action="{% url 'users:login' %}" method="post">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                                            {{ form.username }}
                                        </div>
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.password.id_for_label }}">Пароль</label>
                                            {{ form.password }}
                                        </div>
                                        <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                            <a class="small" href="#">Забыли пароль?</a>
                                            <input class="btn btn-primary" type="submit" value="Авторизоваться">
                                        </div>
                                        <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                            <a href="#">
                                                <i class="fab fa-google fa-2x" style="color: #d9503e;"></i>
                                            </a>
                                            <a href="#">
                                                <i class="fab fa-vk fa-2x" style="color: #4a658b;"></i>
                                            </a>
                                            <a href="{% provider_login_url 'github' %}">
                                                <i class="fab fa-github fa-2x" style="color: #303030;"></i>
                                            </a>
                                            <a href="#">
                                                <i class="fab fa-facebook fa-2x" style="color: #405794;"></i>
                                            </a>
                                        </div>
                                    </form>
                                </div>
                                <div class="card-footer text-center">
                                    <div class="small"><a href="{% url 'users:register' %}">Нужен аккаунт? Зарегистрируйся!</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </div>
{% endblock content %}

users/templates/users/profile.html
{% extends 'olga/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'vendor/css/profile.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-7">
                <h4 class="mt-3 mb-3">Профиль</h4>
                <div class="col-lg-12 text-center">
                    <img width="100" height="100"
                         src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'vendor/img/default_avatar.jpg' %} {% endif %}"
                         class="img-thumbnail">
                </div>
                <form action="{% url 'users:profile' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                {{ form.first_name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                {{ form.last_name }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                {{ form.image }}
                                <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите изображение</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                            {{ form.username }}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                почты</label>
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-5">
                {% if baskets %}
                    <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
                        Корзина <span class="badge badge-secondary badge-pill">{{ baskets.total_quantity }}</span>
                    </h4>
                    {% for basket in baskets %}
                        <div class="card mb-3">
                            <div class="card-body">
                                <h5 class="card-title">{{ basket.product.products }}</h5>
                                <p class="card-text">{{ basket.product.description }}</p>
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item bg-light">
                                    <div class="row text-center">
                                        <div class="col-lg-4">
                                            <input name="basketID" type="number" class="form-control"
                                                   value="{{ basket.quantity }}" min="0">
                                        </div>
                                        <div class="col-lg-4">{{ basket.sum }} руб.</div>
                                        <div class="col-lg-4">
                                            <a href="{% url 'users:basket_remove' basket.id %}">
                                                <i class="fas fa-trash"></i>
                                            </a>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    {% endfor %}
                    <div class="card mb-3">
                        <div class="card-footer">
                            <p class="float-left">Итого</p>
                            <h4 class="float-right">{{ baskets.total_sum }} руб.</h4>
                        </div>
                    </div>
                    <a class="btn btn-success btn-lg float-right" href="{% url 'orders:order_create' %}">
                        Оформить заказ
                    </a>
                {% else %}
                    <h4 class="mt-3 mb-3 text-center">
                        Корзина пуста
                    </h4>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

{% block scripts %}
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>

    <!-- FontAwesome script -->
    <script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>
{% endblock scripts %}

users/templates/users/registration.html
{% extends 'users/base.html' %}
{% load static %}


{% block content %}
	<body class="bg-primary">
		<div id="layoutAuthentication">
			<div id="layoutAuthentication_content">
				<main>
					<div class="container">
						<div class="row justify-content-center">
							<div class="col-lg-7">
								{% if form.errors %}
									<div class="alert alert-warning alert-dismissible fade show" role="alert"
										 style="margin-top: 50px;">
										{{ form.errors }}
										<button type="button" class="close" data-dismiss="alert" aria-label="Close">
											<span aria-hidden="true">&times;</span>
										</button>
									</div>
								{% endif %}
								<div class="card shadow-lg border-0 rounded-lg mt-5">
									<div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
									</div>
									<div class="card-body">
										<form action="{% url 'users:register' %}" method="post">
											{% csrf_token %}
											<div class="form-row">
												<div class="col-md-6">
													<div class="form-group">
														<label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
														{{ form.first_name }}
													</div>
												</div>
												<div class="col-md-6">
													<div class="form-group">
														<label class="small mb-1" for="inputLastName">Фамилия</label>
														{{ form.last_name }}
													</div>
												</div>
											</div>
											<div class="form-row">
												<div class="col-md-6">
													<label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
													{{ form.username }}
												</div>
												<div class="col-md-6">
													<label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
														почты</label>
													{{ form.email }}
												</div>
											</div>
											<div class="form-row">
												<div class="col-md-6">
													<div class="form-group">
														<label class="small mb-1" for="{{ form.password1.id_for_label }}">Пароль</label>
														{{ form.password1 }}
													</div>
												</div>
												<div class="col-md-6">
													<div class="form-group">
														<label class="small mb-1" for="{{ form.password2.id_for_label }}">Подтверждение
															пароля</label>
														{{ form.password2 }}
													</div>
												</div>
											</div>
											<div class="form-group mt-4 mb-0">
												<input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
											</div>
										</form>
									</div>
									<div class="card-footer text-center">
										<div class="small"><a href="{% url 'users:login' %}">Уже есть аккаунт? Авторизоваться</a></div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</main>
			</div>
		</div>
		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
				crossorigin="anonymous"></script>
		<script src="{% static 'vendor/js/auth-admin.js' %}"></script>
	</body>
{% endblock content %}